[SOC-Detect-Deserialization]
search = index=* sourcetype="httpevent" ("O:" OR "a:" OR "r:" OR "S:" OR "java.lang.Runtime")
description = Proqramlasdirma dillerinde obyektlerin seriyalasdirilmasi zamani kod icra etme cehdi.
