[SOC-Detect-Command-Injection]
search = index=* (sourcetype="httpevent" OR sourcetype="docker_logs") ("; id" OR "; whoami" OR "; cat /etc/" OR "&& ipconfig")
description = Web proqram uzerinden emeliyyat sistemi emrlerinin yeridilmesi cehdi.
