[SOC-Detect-IDOR]
search = index=* sourcetype="httpevent" | stats dc(url) as unique_urls by src_ip | where unique_urls > 100
description = Bir istifadecinin qisa muddetde yuzlerle ferqli ID-li (user_id=1, 2, 3...) sehifeye muraciet etmesi.
