[SOC-Detect-LFI]
search = index=* sourcetype="httpevent" ("php://filter" OR "expect://" OR "input://" OR "filename=../../")
description = Server daxili fayllarin (config, passwd) proqram vasitesile oxunmasi cehdi.
