[SOC-Detect-Sensitive-Files]
search = index=* sourcetype="httpevent" (".env" OR ".git/" OR "config.php.bak" OR "wp-config.php" OR ".htaccess")
description = Serverdeki hesas tenzimleme ve ya versiya nezareti fayllarina giris cehdi.
