[Web_Shell_Execution]
search = index=* sourcetype="docker_logs" (file_name="*.php" OR file_name="*.jsp") (cmd OR shell OR passthru)
description = Web serverde subheli emrlerin (WebShell) icra olunmasi.
