[Web_Path_Traversal]
search = index=* (sourcetype="docker_logs" OR sourcetype="httpevent") ("../" OR "/etc/passwd" OR "/windows/system32")
description = Sistem fayllarina icazesiz giris cehdi (Path Traversal).
